version: '3'
services:

  keycloak:
    container_name: keycloak
    image: quay.io/snimmo/ocp-keycloak:latest
    #image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin